
language: cpp
dist: focal
jobs:
  include:
    - os: linux
      name: "Linux (DEB, RPM)"
      addons:
        apt:
          packages:
            - rpm
            - dpkg
      script:
        - cmake -H. -B_build -DCMAKE_BUILD_TYPE=Release -DCPACK_GENERATOR="DEB;RPM"
        - cmake --build _build --config Release
        - cd _build
        - cpack -G DEB
        - cpack -G RPM
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file_glob: true
        file: _build/*.{deb,rpm}
        skip_cleanup: true
        on:
          tags: true
